/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ControlRouteImport } from './routes/control'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.xml]'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.xml]'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ControlIndexRouteImport } from './routes/control.index'
import { Route as ControlLoginRouteImport } from './routes/control.login'
import { Route as ArchiveCivilizationsIdRouteImport } from './routes/archive.civilizations.$id'
import { Route as DocsArchitectureFilenameRouteImport } from './routes/docs.architecture.$filename'
import { Route as ApiV1AdminAuthRouteImport } from './routes/api/v1/admin/auth'
import { Route as ApiV1AdminExperimentsUploadRouteImport } from './routes/api/v1/admin/experiments/upload'
import { Route as ApiV1AdminExperimentsStagingIdPublishRouteImport } from './routes/api/v1/admin/experiments/$stagingId/publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ControlIndexRoute = ControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRoute,
} as any)
const ControlLoginRoute = ControlLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ControlRoute,
} as any)
const ArchiveCivilizationsIdRoute = ArchiveCivilizationsIdRouteImport.update({
  id: '/civilizations/$id',
  path: '/civilizations/$id',
  getParentRoute: () => ArchiveRoute,
} as any)
const DocsArchitectureFilenameRoute =
  DocsArchitectureFilenameRouteImport.update({
    id: '/docs/architecture/$filename',
    path: '/docs/architecture/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminAuthRoute = ApiV1AdminAuthRouteImport.update({
  id: '/api/v1/admin/auth',
  path: '/api/v1/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminExperimentsUploadRoute =
  ApiV1AdminExperimentsUploadRouteImport.update({
    id: '/api/v1/admin/experiments/upload',
    path: '/api/v1/admin/experiments/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminExperimentsStagingIdPublishRoute =
  ApiV1AdminExperimentsStagingIdPublishRouteImport.update({
    id: '/api/v1/admin/experiments/$stagingId/publish',
    path: '/api/v1/admin/experiments/$stagingId/publish',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/control': typeof ControlRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/control/login': typeof ControlLoginRoute
  '/archive/': typeof ArchiveIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/control/': typeof ControlIndexRoute
  '/archive/civilizations/$id': typeof ArchiveCivilizationsIdRoute
  '/docs/architecture/$filename': typeof DocsArchitectureFilenameRoute
  '/api/v1/admin/auth': typeof ApiV1AdminAuthRoute
  '/api/v1/admin/experiments/upload': typeof ApiV1AdminExperimentsUploadRoute
  '/api/v1/admin/experiments/$stagingId/publish': typeof ApiV1AdminExperimentsStagingIdPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/control/login': typeof ControlLoginRoute
  '/archive': typeof ArchiveIndexRoute
  '/blog': typeof BlogIndexRoute
  '/control': typeof ControlIndexRoute
  '/archive/civilizations/$id': typeof ArchiveCivilizationsIdRoute
  '/docs/architecture/$filename': typeof DocsArchitectureFilenameRoute
  '/api/v1/admin/auth': typeof ApiV1AdminAuthRoute
  '/api/v1/admin/experiments/upload': typeof ApiV1AdminExperimentsUploadRoute
  '/api/v1/admin/experiments/$stagingId/publish': typeof ApiV1AdminExperimentsStagingIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/control': typeof ControlRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/control/login': typeof ControlLoginRoute
  '/archive/': typeof ArchiveIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/control/': typeof ControlIndexRoute
  '/archive/civilizations/$id': typeof ArchiveCivilizationsIdRoute
  '/docs/architecture/$filename': typeof DocsArchitectureFilenameRoute
  '/api/v1/admin/auth': typeof ApiV1AdminAuthRoute
  '/api/v1/admin/experiments/upload': typeof ApiV1AdminExperimentsUploadRoute
  '/api/v1/admin/experiments/$stagingId/publish': typeof ApiV1AdminExperimentsStagingIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/blog'
    | '/control'
    | '/sitemap.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/control/login'
    | '/archive/'
    | '/blog/'
    | '/control/'
    | '/archive/civilizations/$id'
    | '/docs/architecture/$filename'
    | '/api/v1/admin/auth'
    | '/api/v1/admin/experiments/upload'
    | '/api/v1/admin/experiments/$stagingId/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/control/login'
    | '/archive'
    | '/blog'
    | '/control'
    | '/archive/civilizations/$id'
    | '/docs/architecture/$filename'
    | '/api/v1/admin/auth'
    | '/api/v1/admin/experiments/upload'
    | '/api/v1/admin/experiments/$stagingId/publish'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/blog'
    | '/control'
    | '/sitemap.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/control/login'
    | '/archive/'
    | '/blog/'
    | '/control/'
    | '/archive/civilizations/$id'
    | '/docs/architecture/$filename'
    | '/api/v1/admin/auth'
    | '/api/v1/admin/experiments/upload'
    | '/api/v1/admin/experiments/$stagingId/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ControlRoute: typeof ControlRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  DocsArchitectureFilenameRoute: typeof DocsArchitectureFilenameRoute
  ApiV1AdminAuthRoute: typeof ApiV1AdminAuthRoute
  ApiV1AdminExperimentsUploadRoute: typeof ApiV1AdminExperimentsUploadRoute
  ApiV1AdminExperimentsStagingIdPublishRoute: typeof ApiV1AdminExperimentsStagingIdPublishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/control/': {
      id: '/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof ControlIndexRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/login': {
      id: '/control/login'
      path: '/login'
      fullPath: '/control/login'
      preLoaderRoute: typeof ControlLoginRouteImport
      parentRoute: typeof ControlRoute
    }
    '/archive/civilizations/$id': {
      id: '/archive/civilizations/$id'
      path: '/civilizations/$id'
      fullPath: '/archive/civilizations/$id'
      preLoaderRoute: typeof ArchiveCivilizationsIdRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/docs/architecture/$filename': {
      id: '/docs/architecture/$filename'
      path: '/docs/architecture/$filename'
      fullPath: '/docs/architecture/$filename'
      preLoaderRoute: typeof DocsArchitectureFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/auth': {
      id: '/api/v1/admin/auth'
      path: '/api/v1/admin/auth'
      fullPath: '/api/v1/admin/auth'
      preLoaderRoute: typeof ApiV1AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/experiments/upload': {
      id: '/api/v1/admin/experiments/upload'
      path: '/api/v1/admin/experiments/upload'
      fullPath: '/api/v1/admin/experiments/upload'
      preLoaderRoute: typeof ApiV1AdminExperimentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/experiments/$stagingId/publish': {
      id: '/api/v1/admin/experiments/$stagingId/publish'
      path: '/api/v1/admin/experiments/$stagingId/publish'
      fullPath: '/api/v1/admin/experiments/$stagingId/publish'
      preLoaderRoute: typeof ApiV1AdminExperimentsStagingIdPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ArchiveCivilizationsIdRoute: typeof ArchiveCivilizationsIdRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveIndexRoute: ArchiveIndexRoute,
  ArchiveCivilizationsIdRoute: ArchiveCivilizationsIdRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ControlRouteChildren {
  ControlLoginRoute: typeof ControlLoginRoute
  ControlIndexRoute: typeof ControlIndexRoute
}

const ControlRouteChildren: ControlRouteChildren = {
  ControlLoginRoute: ControlLoginRoute,
  ControlIndexRoute: ControlIndexRoute,
}

const ControlRouteWithChildren =
  ControlRoute._addFileChildren(ControlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ControlRoute: ControlRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  DocsArchitectureFilenameRoute: DocsArchitectureFilenameRoute,
  ApiV1AdminAuthRoute: ApiV1AdminAuthRoute,
  ApiV1AdminExperimentsUploadRoute: ApiV1AdminExperimentsUploadRoute,
  ApiV1AdminExperimentsStagingIdPublishRoute:
    ApiV1AdminExperimentsStagingIdPublishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
